version: '3'
services:
  web: 
    #build:
    #  context: .
    #  dockerfile: Dockerfile.dev
    image: ozgur/web-test
    ports:
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
  tests:
    image: ozgur/web 
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm", "run", "test"]